# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\login_logout.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from api.login_api_test import TestCaseLoginApi as LoginApi


class TestCaseLoginLogout(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "case-account-password-expect": [
                    ["正常登陆", "admin", "test123", "parent.location='/zentao/';"],
                    ["密码为空", "lisensen", "", "", "登录失败，请检查您的用户名或密码是否填写正确"],
                    ["密码错误", "liss", "333333", "登录失败，请检查您的用户名或密码是否填写正确"],
                    ["账号不存在", "test", "333333", "登录失败，请检查您的用户名或密码是否填写正确"],
                    ["账号为空", "", "333333", "登录失败，请检查您的用户名或密码是否填写正确"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("testcase description").base_url("${ENV(HOST)}")

    teststeps = [
        Step(RunTestCase("login_$case").call(LoginApi)),
    ]


if __name__ == "__main__":
    TestCaseLoginLogout().test_start()
