# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\bug_detial.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseBugDetial(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/zentao/bug-view-1.html")
            .get("http://127.0.0.1/zentao/bug-view-1.html")
            .with_headers(
                **{
                    "Host": "127.0.0.1",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-User": "?1",
                    "Sec-Fetch-Dest": "document",
                    "Referer": "http://127.0.0.1/zentao/bug-browse-1.html",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
                    "Cookie": "lang=zh-cn; theme=default; preBranch=0; bugModule=0; qaBugOrder=id_desc; preProductID=1; lastProduct=1; lastProject=1; preProjectID=1; moduleBrowseParam=0; productBrowseParam=0; projectTaskOrder=status%2Cid_desc; caseModule=0; windowWidth=1519; windowHeight=754; zentaosid=e3r590i5dkg87dgbrn2nm3q0q5",
                }
            )
            .with_cookies(
                **{
                    "lang": "zh-cn",
                    "theme": "default",
                    "preBranch": "0",
                    "bugModule": "0",
                    "qaBugOrder": "id_desc",
                    "preProductID": "1",
                    "lastProduct": "1",
                    "lastProject": "1",
                    "preProjectID": "1",
                    "moduleBrowseParam": "0",
                    "productBrowseParam": "0",
                    "projectTaskOrder": "status%2Cid_desc",
                    "caseModule": "0",
                    "windowWidth": "1519",
                    "windowHeight": "754",
                    "zentaosid": "e3r590i5dkg87dgbrn2nm3q0q5",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html; Language=UTF-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseBugDetial().test_start()
