# NOTE: Generated By HttpRunner v3.1.4
# FROM: api\login_api.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginApi(HttpRunner):

    config = Config("testcase description").base_url("${ENV(HOST)}")

    teststeps = [
        Step(
            RunRequest("login_$case")
            .post("/zentao/user-login-L3plbnRhby8=.html")
            .with_headers(
                **{
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Sec-Fetch-Dest": "iframe",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63",
                }
            )
            .with_data(
                {"account": "$account", "password": "$password", "referer": "/zentao/"}
            )
            .validate()
            .assert_contains("text", "$expect")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginApi().test_start()
